-- MySQL Script generated by MySQL Workbench
-- Thu Feb 13 10:38:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_SICAFIT
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BD_SICAFIT` ;

-- -----------------------------------------------------
-- Schema BD_SICAFIT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_SICAFIT` DEFAULT CHARACTER SET utf8 ;
USE `BD_SICAFIT` ;

-- -----------------------------------------------------
-- Table `BD_SICAFIT`.`tm_backup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SICAFIT`.`tm_backup` (
  `back_id` INT NOT NULL AUTO_INCREMENT,
  `back_date_new` DATETIME NULL,
  `back_date_edit` DATETIME NULL,
  `back_date_delete` DATETIME NULL,
  `back_name` VARCHAR(255) NULL,
  `back_status` VARCHAR(1) NULL,
  `usu_id` INT NOT NULL,
  PRIMARY KEY (`back_id`),
  CONSTRAINT `FK_TM_USU_ID_BACKUP_TM`
    FOREIGN KEY (`usu_id`)
    REFERENCES `BD_SICAFIT`.`tm_usuarios` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SICAFIT`.`tm_casos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SICAFIT`.`tm_casos` (
  `caso_id` INT NOT NULL AUTO_INCREMENT,
  `caso_date_and_hour` DATETIME NULL,
  `caso_place` VARCHAR(255) NULL,
  `caso_state_situational` VARCHAR(85) NULL,
  `caso_protect_victim` VARCHAR(85) NULL,
  `caso_date_new` DATETIME NULL,
  `caso_date_edit` DATETIME NULL,
  `caso_date_delete` DATETIME NULL,
  `caso_status` VARCHAR(1) NULL,
  `usu_id` INT NOT NULL,
  `deli_id` INT NOT NULL,
  PRIMARY KEY (`caso_id`),
  CONSTRAINT `FK_TM_DETE_CASOS`
    FOREIGN KEY (`usu_id`)
    REFERENCES `BD_SICAFIT`.`tm_usuarios` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TM_DELI_CASOS`
    FOREIGN KEY (`deli_id`)
    REFERENCES `BD_SICAFIT`.`tm_delitos` (`deli_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SICAFIT`.`tm_categorias_delitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SICAFIT`.`tm_categorias_delitos` (
  `cate_deli_id` INT NOT NULL AUTO_INCREMENT,
  `cate_deli_name` VARCHAR(255) NULL,
  `cate_deli_date_new` DATETIME NULL,
  `cate_deli_date_edit` DATETIME NULL,
  `cate_deli_date_delete` DATETIME NULL,
  `cate_deli_status` VARCHAR(1) NULL,
  PRIMARY KEY (`cate_deli_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SICAFIT`.`tm_delitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SICAFIT`.`tm_delitos` (
  `deli_id` INT NOT NULL AUTO_INCREMENT,
  `deli_name` VARCHAR(255) NULL,
  `deli_description` VARCHAR(255) NULL,
  `deli_date_new` DATETIME NULL,
  `deli_date_edit` DATETIME NULL,
  `deli_date_delete` DATETIME NULL,
  `deli_status` VARCHAR(1) NULL,
  `usu_id` INT NOT NULL,
  `cate_deli_id` INT NOT NULL,
  PRIMARY KEY (`deli_id`),
  CONSTRAINT `FK_USU_ID_DELITOS`
    FOREIGN KEY (`usu_id`)
    REFERENCES `BD_SICAFIT`.`tm_usuarios` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CATE_DELI_ID`
    FOREIGN KEY (`cate_deli_id`)
    REFERENCES `BD_SICAFIT`.`tm_categorias_delitos` (`cate_deli_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SICAFIT`.`tm_dependencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SICAFIT`.`tm_dependencias` (
  `depen_id` INT NOT NULL AUTO_INCREMENT,
  `depen_name` VARCHAR(255) NULL,
  `depen_description` VARCHAR(255) NULL,
  `depen_date_new` DATETIME NULL,
  `depen_date_edit` DATETIME NULL,
  `depen_date_delete` DATETIME NULL,
  `depen_status` VARCHAR(1) NULL,
  `sede_id` INT NOT NULL,
  `usu_id` INT NOT NULL,
  PRIMARY KEY (`depen_id`),
  CONSTRAINT `FK_SEDE_ID_DEPENDENCIA`
    FOREIGN KEY (`sede_id`)
    REFERENCES `BD_SICAFIT`.`tm_sedes` (`sede_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USU_ID_DEPENDENCIA`
    FOREIGN KEY (`usu_id`)
    REFERENCES `BD_SICAFIT`.`tm_usuarios` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SICAFIT`.`tm_detenidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SICAFIT`.`tm_detenidos` (
  `dete_id` INT NOT NULL AUTO_INCREMENT,
  `dete_name` VARCHAR(80) NULL,
  `dete_last_name` VARCHAR(80) NULL,
  `dete_age` VARCHAR(100) NULL,
  `dete_dni` CHAR(8) NULL,
  `dete_date_new` DATETIME NULL,
  `dete_date_edit` DATETIME NULL,
  `dete_date_delete` DATETIME NULL,
  `dete_status` VARCHAR(1) NULL,
  `caso_id` INT NOT NULL,
  PRIMARY KEY (`dete_id`),
  CONSTRAINT `FK_CASO_ID_DETENIDOS`
    FOREIGN KEY (`caso_id`)
    REFERENCES `BD_SICAFIT`.`tm_casos` (`caso_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SICAFIT`.`tm_locales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SICAFIT`.`tm_locales` (
  `loca_id` INT NOT NULL AUTO_INCREMENT,
  `loca_name` VARCHAR(255) NULL,
  `loca_address` VARCHAR(255) NULL,
  `loca_date_new` DATETIME NULL,
  `loca_date_edit` DATETIME NULL,
  `loca_date_delete` DATETIME NULL,
  `loca_status` VARCHAR(1) NULL,
  `usu_id` INT NOT NULL,
  PRIMARY KEY (`loca_id`),
  CONSTRAINT `FK_USU_ID_LOCAL`
    FOREIGN KEY (`usu_id`)
    REFERENCES `BD_SICAFIT`.`tm_usuarios` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SICAFIT`.`tm_sedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SICAFIT`.`tm_sedes` (
  `sede_id` INT NOT NULL AUTO_INCREMENT,
  `sede_name` VARCHAR(255) NULL,
  `sede_date_new` DATETIME NULL,
  `sede_date_edit` DATETIME NULL,
  `sede_date_delete` DATETIME NULL,
  `sede_status` VARCHAR(1) NULL,
  `loca_id` INT NOT NULL,
  `usu_id` INT NOT NULL,
  PRIMARY KEY (`sede_id`),
  CONSTRAINT `FK_LOCA_ID_SEDE`
    FOREIGN KEY (`loca_id`)
    REFERENCES `BD_SICAFIT`.`tm_locales` (`loca_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USU_ID_SEDE`
    FOREIGN KEY (`usu_id`)
    REFERENCES `BD_SICAFIT`.`tm_usuarios` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SICAFIT`.`tm_ubigeo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SICAFIT`.`tm_ubigeo` (
  `ubi_id` INT NOT NULL AUTO_INCREMENT,
  `ubi_departament` VARCHAR(200) NULL,
  `ubi_province` VARCHAR(200) NULL,
  `ubi_district` VARCHAR(200) NULL,
  `ubi_date_new` DATETIME NULL,
  `ubi_date_edit` DATETIME NULL,
  `ubi_date_delete` DATETIME NULL,
  `ubi_status` VARCHAR(1) NULL,
  `usu_id` INT NOT NULL,
  PRIMARY KEY (`ubi_id`),
  CONSTRAINT `FK_USU_ID_UBIGEO`
    FOREIGN KEY (`usu_id`)
    REFERENCES `BD_SICAFIT`.`tm_usuarios` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SICAFIT`.`tm_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SICAFIT`.`tm_usuarios` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_name` VARCHAR(80) NULL,
  `last_name` VARCHAR(85) NULL,
  `usu_dni` CHAR(8) NULL,
  `usu_rol` VARCHAR(40) NULL,
  `usu_password` VARCHAR(80) NULL,
  `usu_date_new` DATETIME NULL,
  `usu_date_edit` DATETIME NULL,
  `usu_date_delete` DATETIME NULL,
  `usu_status` VARCHAR(1) NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
